esphome:
  name: shelly-uni-recovery

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
#api:
#  encryption:
#    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
