substitutions:
  devicename: "growatt"
  upper_devicename: "ESPHome Growatt 01"

esphome:
  name: "${devicename}"
  platform: ESP8266
  board: esp07s

logger:
  baud_rate: 0

api:
  password: "vlBpyX#7jSI5"

ota:
  - platform: esphome
    password: "vlBpyX#7jSI5"

wifi:
  ssid: "HIOT"
  password: "28474172737459768132958148552971"
  fast_connect: true
  power_save_mode: none

uart:
  id: mod_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 115200

modbus:
  id: modbus1
  uart_id: mod_bus

modbus_controller:
  - id: growatt
    address: 0x01
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 5s

# --- JSON SCHNITTSTELLE (Optimistic, kein on_boot) ---
text:
  - platform: template
    name: "Growatt Config Payload"
    id: growatt_config_payload
    optimistic: true
    mode: text
    on_value:
      then:
        - lambda: |-
            ESP_LOGI("JSON_ANALYSIS", "Empfangen: %s", x.c_str());

# --- READ-ONLY SENSOREN ---
text_sensor:
  - platform: modbus_controller
    name: "${devicename} Firmware Version"
    address: 9
    register_count: 3
    register_type: holding
  - platform: modbus_controller
    name: "${devicename} Serial Number"
    address: 23
    register_count: 5
    register_type: holding

sensor:
  - platform: modbus_controller
    name: "Battery charge status"
    address: 1014
    register_type: "read"
    value_type: U_WORD
    unit_of_measurement: "%"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s