esphome:
  name: esphome-web-6c3fa4
  friendly_name: Garage G32
  includes:
    - a02yyuw_g32.h

esp32:
  board: esp32dev
  framework:
    type: arduino


# Enable Home Assistant API
api:
  encryption:
    key: "mcJEiTGtn9fvpuHu8T5B8nIa8xrToPVRlNeO+Ke/2lE="

ota:
  password: "6da3b19a6645d31de7652ab43dfaafd4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-G32 Fallback Hotspot"
    password: "DvVemIlpiB3n"

# Enable Web server
web_server:
  port: 80

captive_portal:
    
# Logging aktivieren
logger:
  #level: ERROR
  #baud_rate: 0  # Deaktiviert Standard-Logs auf UART

uart:
  id: uart_bus
  tx_pin: GPIO14
  rx_pin: GPIO27
  baud_rate: 9600

# Custom Sensor Component
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new A02YYUW(id(uart_bus));
      App.register_component(my_sensor);
      return {my_sensor->distance_sensor};
    sensors:
      - name: "A02YYUW Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 1
        icon: "mdi:ruler"