esphome:
  name: garagen-steuerung-rechts
  friendly_name: Garagen Steuerung Rechts
  includes:
    - a02yyuw.h


esp8266:
  board: d1_mini 

# Enable Home Assistant API
api:
  encryption:
    key: "qbjaZXUIsaYMzuvj9rvfDA5vuKNf57xOj4t0I0PmAvs="

ota:
  password: "c06c6f63f86fed1c5dedbf87ac618f25"  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garagen-Steuerung-Rechts"
    password: "k9LCj15Gx0BV"

# Enable Web server
web_server:
  port: 80

captive_portal:

# UART für den Sensor

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 #disable logging over uart

# Benutzerdefinierter Sensor
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new A02YYUW(id(uart_bus));
      App.register_component(my_sensor);
      return {my_sensor->distance_sensor};
    sensors:
      - name: "A02YYUW Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 1