esphome:
  name: garage-g32
  friendly_name: Garage G32
  includes:
    - a02yyuw_g32.h
  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
api:
  encryption:
    key: "AjezBesTY02VlrxAj7Yyx3xYyx0PlFKMZYloVIObuIY="

ota:
  password: "6da3b19a6645d31de7652ab43dfaafd4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-G32 Fallback Hotspot"
    password: "DvVemIlpiB3n"

captive_portal:
    
# Logging aktivieren
logger:
  level: DEBUG
  baud_rate: 0  # Deaktiviert Standard-Logs auf UART

# UART-Schnittstelle für den Sensor
uart:
  tx_pin: GPIO17  # Anpassen je nach Anschluss
  rx_pin: GPIO16  # Anpassen je nach Anschluss
  baud_rate: 9600
  id: uart_bus

# Benutzerdefinierte Komponente für den Sensor
sensor:
  - platform: custom
    lambda: |-
      auto my_sensor = new A02YYUW(id(uart_bus));
      App.register_component(my_sensor);
      return {my_sensor->distance_sensor};
    sensors:
      - name: "A02YYUW Distance"
        unit_of_measurement: "cm"
        accuracy_decimals: 1
