esphome:
  name: ina-test
  friendly_name: INA-Test
    
esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: DEBUG
  logs:
    sensor: ERROR  
    adc: WARN      
    mqtt: DEBUG    
    text_sensor: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: "rbmRAmvNueeCSUYZPddorXvP00d48gXUJoF2RwFL1J4="

ota:
  password: "8de4171f7e36e293ecc1fed07933f2fb"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.24.179
    gateway: 192.168.24.1
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Pergolux Fallback Hotspot"
    password: "PUAVjKK8gxY8"

# Enable Web server
web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO2
    id: WiFi_led
    inverted: yes   


i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true  # Optional: Aktiviert das Scannen der I2C-Geräte für Debugging

sensor:
  - platform: ina219
    address: 0x40  # Standardadresse des INA219, passe sie an, falls nötig
    shunt_resistance: 0.1  # Standard-Shunt-Widerstand (Ohm)
    update_interval: 250ms
    current:
      name: "Strom (mA)"
      unit_of_measurement: "mA"
      accuracy_decimals: 3

    power:
      name: "Leistung (mW)"
      unit_of_measurement: "mW"
      accuracy_decimals: 3

    bus_voltage:
      name: "Bus-Spannung (V)"
      unit_of_measurement: "V"
      accuracy_decimals: 3

    shunt_voltage:
      name: "Shunt-Spannung (mV)"
      unit_of_measurement: "mV"
      accuracy_decimals: 3    

interval: 

  # Wifi Status
  - interval: 250ms
    then:
      if:
        condition:
          wifi.connected:
        then:
          - output.turn_on: WiFi_led
        else:
          - output.turn_on: WiFi_led
          - delay: 125ms
          - output.turn_off: WiFi_led   