esphome:
  name: mbus-gartenzaehler
  platform: ESP8266
  board: esp01_1m

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  password: "vlBpyX#7jSI5"
  
ota:
  password: "vlBpyX#7jSI5"

wifi:
  ssid: "HIOT"
  password: "28474172737459768132958148552971"

  #manual_ip:
  #  static_ip: 192.168.24.209
  #  gateway: 192.168.24.1
  #  subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "mbus-gartenzaehler"
    password: "Ipg6xkQSsmlH"

# Enable Web server
web_server:
  port: 80

captive_portal:

sensor:
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    update_interval: 1s

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 5s

text_sensor:
- platform: wifi_info
  ip_address: 
    name: IPAddress
  ssid:
    name: SSID
  bssid:
    name: BSSID
  mac_address:
    name: Mac   

switch:
  - platform: gpio
    name: "GPIO0 Switch"
    pin: GPIO0
    id: gpio0_switch

interval:
  - interval: 3s
    then:
      - switch.turn_on: gpio0_switch
      - delay: 1s
      - switch.turn_off: gpio0_switch