esphome:
  name: robbyumschalter
  platform: ESP8266
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "vlBpyX#7jSI5"

ota:
  password: "vlBpyX#7jSI5"

wifi:
  ssid: "HIOT"
  password: "28474172737459768132958148552971"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Robbyumschalter Fallback Hotspot"
    password: "WLlNFoAbjilQ"

# Enable Web server
web_server:
  port: 80
    
text_sensor:
- platform: wifi_info
  ip_address: 
    name: ESP IP Address
  ssid:
    name: ESP Connected SSID
  bssid:
    name: ESP Connected BSSID
  mac_address:
    name: ESP Mac Wifi Address

captive_portal:

switch:
  - platform: gpio
    #inverted: True
    name: "Relay0"
    pin: GPIO5
    id: relay0

  - platform: gpio
    #inverted: True
    name: "Relay1"
    pin: GPIO12
    id: relay1
    on_turn_off:
      - switch.turn_off: relay0
    on_turn_on:
      - switch.turn_on:  relay0

  - platform: gpio
    inverted: True
    name: "LED"
    pin: GPIO13
    
sensor:
- platform: wifi_signal
  name: "WiFi Signal Sensor"
  update_interval: 60s
