esphome:
  name: robby-zone
  friendly_name: Robby Zone

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SZs2PfSWa85mDS3ocvm1HjNILKRADGhMAsmNHDJaENA="

ota:
  password: "0af6fac20b4f654cfe7daae59ddf16dc"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Robby-Zone Fallback Hotspot"
    password: "fcSmRxNnpcxz"

captive_portal:
    